server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/pgfinder_db
spring.datasource.username=root
spring.datasource.password=cdac
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app.jwt-expiration-milliseconds=604800000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# REPLACE 'root' WITH YOUR REAL GMAIL ADDRESS (e.g. user@gmail.com)
spring.mail.username=bhujbalshamal7@gmail.com
# REPLACE 'cdac' WITH YOUR GMAIL APP PASSWORD (generate from Google Account > Security > App Passwords)
spring.mail.password=ecwmpblvmglvzakg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
