# Server Configuration
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/PGFinderDB1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=cdac
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=YourSuperSecretKeyThatIsAtLeast32CharactersLong!
jwt.expiration=604800000
jwt.issuer=PGFinderAPI
jwt.audience=PGFinderClient
